POST http://localhost:3333/livro
Content-Type: application/json

{
    "titulo": "jordan: 02",
    "autor": "nike: 02",
    "npaginas": 1000 (pares)

}

###

GET http://localhost:3333/livro

###

GET http://localhost:3333/livro?search=IFMS

###

PUT http://localhost:3333/livro/5aea1252-ee29-4cae-9bc3-04f330403d85
Content-Type: application/json 

{
    "titulo": "Livro IFMS",
    "autor": "Autor: Luís",
    "npaginas": 100
}

###

DELETE http://localhost:3333/livro/5aea1252-ee29-4cae-9bc3-04f330403d85